# Generated by Django 5.1.2 on 2024-10-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='option_one',
            field=models.CharField(default='Option 1', max_length=200),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_three',
            field=models.CharField(default='Option 3', max_length=100),
        ),
        migrations.AddField(
            model_name='poll',
            name='option_two',
            field=models.CharField(default='Option 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
